# Generated by Django 3.1.1 on 2021-06-14 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmChannel',
            fields=[
                ('channel_id', models.CharField(max_length=34, primary_key=True, serialize=False, unique=True, verbose_name='渠道id')),
                ('channel_type', models.CharField(max_length=34, verbose_name='渠道类型')),
                ('channel_name', models.CharField(max_length=255, unique=True, verbose_name='渠道名称')),
                ('channel_access', models.CharField(max_length=1000, unique=True, verbose_name='渠道地址')),
                ('channel_webhook', models.CharField(max_length=255, unique=True, verbose_name='平台webhook地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('create_user', models.CharField(default='admin', max_length=255, verbose_name='创建人')),
                ('update_user', models.CharField(default='admin', max_length=255, verbose_name='更新人')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationLevelTwoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_one_name', models.CharField(max_length=255, verbose_name='一级标题名称')),
                ('level_two_name', models.CharField(max_length=255, unique=True, verbose_name='二级标题名称')),
                ('level_two_type', models.CharField(max_length=255, unique=True, verbose_name='二级标题类型')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_one_name', models.CharField(max_length=255, unique=True, verbose_name='一级标题名称')),
            ],
        ),
    ]
