# Generated by Django 3.1.1 on 2021-06-09 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmChannel',
            fields=[
                ('channel_id', models.CharField(max_length=34, primary_key=True, serialize=False, unique=True, verbose_name='渠道id')),
                ('channel_type', models.CharField(max_length=34, verbose_name='渠道类型')),
                ('channel_name', models.CharField(max_length=255, unique=True, verbose_name='渠道名称')),
                ('channel_access', models.CharField(max_length=1000, unique=True, verbose_name='渠道地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('create_user', models.CharField(default='admin', max_length=255, verbose_name='创建人')),
                ('update_user', models.CharField(default='admin', max_length=255, verbose_name='更新人')),
            ],
        ),
    ]
