# Generated by Django 3.1.1 on 2021-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlarm', '0002_alarmtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmchannel',
            name='template_name',
            field=models.CharField(default='aaaa', max_length=32, verbose_name='模板id'),
            preserve_default=False,
        ),
    ]
