# Generated by Django 3.1.1 on 2021-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlarm', '0003_alarmchannel_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmchannel',
            name='template_name',
            field=models.CharField(max_length=255, verbose_name='模板名称'),
        ),
    ]
