# Generated by Django 3.1.1 on 2021-06-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlarm', '0004_auto_20210620_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmchannel',
            name='template_name',
        ),
        migrations.AddField(
            model_name='alarmchannel',
            name='alarm_template_name',
            field=models.CharField(default='aaa', max_length=255, verbose_name='告警模板名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmchannel',
            name='restore_template_name',
            field=models.CharField(default='aaa', max_length=255, verbose_name='恢复模板名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmtemplate',
            name='channel_type',
            field=models.CharField(default='weixin', max_length=34, verbose_name='渠道类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmtemplate',
            name='template_content',
            field=models.CharField(max_length=5000, verbose_name='模板地址'),
        ),
        migrations.AlterField(
            model_name='alarmtemplate',
            name='template_id',
            field=models.CharField(max_length=34, primary_key=True, serialize=False, unique=True, verbose_name='模板id'),
        ),
        migrations.AlterField(
            model_name='alarmtemplate',
            name='template_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='alarmtemplate',
            name='template_type',
            field=models.CharField(max_length=34, verbose_name='模板类型'),
        ),
    ]
