# Generated by Django 3.1.1 on 2021-07-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlarm', '0005_auto_20210629_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmtemplate',
            name='notify_type',
            field=models.CharField(default='markdown', max_length=5000, verbose_name='通知形式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmtemplate',
            name='template_content',
            field=models.CharField(max_length=5000, verbose_name='模板内容'),
        ),
    ]
